### ISSUE TITLE
move bot action to webcompat server

### ISSUE THREAD

**Issue by hallvors** [webcompat/web-bugs-issue-tagger#10]
for easier access to a shared DB ("from webcompat import engine")

**Comment by miketaylr** [comment]
Right now the bot uses gunicorn, so gonna look into what it will take to integrate into our uwsgi setup. Might be pretty simple using http://uwsgi-docs.readthedocs.org/en/latest/Emperor.html.

**Comment by miketaylr** [comment]
Actually. Let's move this whole thing into the webcompat app.

**Comment by karlcow** [comment]
:/ not sure it's a good idea.

**Comment by miketaylr** [comment]
Why?
