### ISSUE TITLE
Don't add browser version to label

### ISSUE THREAD

**Issue by miketaylr** [webcompat/web-bugs-issue-tagger#7]
Right now, `set_label` will grab everything in the foo from `<!-- @browser: foo -->`, append `browser-` to it and set that as the label. So if you have `@browser: foo nightly 41` you get `browser-foo-nightly-41` which isn't great.

**Comment by miketaylr** [comment]
We populate @browser from Browser / Version field, which maybe isn't the best idea.

Maybe we should run ua_parser on the UA string and grab the family name instead (possibly matching against a whitelist)? Right now if you put in "Cool Guy Foo" it'll create a `browser-cool-guy-foo` label which is spam.

**Comment by miketaylr** [comment]
Thoughts @karlcow?

**Comment by miketaylr** [comment]
To clarify:

> Maybe we should run ua_parser on the UA string and grab the family name instead (possibly matching against a whitelist)?

That's how we get 1/2 of the "Browser / Version" field. So this would be doing the same and just ignoring the version.

**Comment by karlcow** [comment]
@miketaylr 

```js
match_list = re.search(r'<!--\s@(\w+):\s([^\d]+?)\s\d+.\d+\s-->', body)
```

This is [working too](https://regex101.com/r/lY9xC8/1).

![capture d ecran 2015-07-30 a 07 19 45](https://cloud.githubusercontent.com/assets/505230/8971462/a9cd5b02-368b-11e5-94d2-6b7f0fa140e7.png)

**Comment by karlcow** [comment]
ok my bad it was failing with things like `Opera Mobile 31.0.1890`. [Updated the regex](https://regex101.com/r/lY9xC8/2)

```js
match_list = re.search(r'<!--\s@(\w+):\s([^\d]+?)\s[\d\.]+\s-->', body)
```

**Comment by karlcow** [comment]
Additional possibilites.

* `<!--\s@browser:\s([^\d]+?)\s[\d\.]+\s-->` aka match browser without a group
* `<!--\s@\w+:\s([^\d]+?)\s[\d\.]+\s-->` aka match browser in a more loosely way without a group

**Comment by miketaylr** [comment]
@karlcow the updated regex looks good, thanks!. ^_^ If you want to commit that, I can push to Heroku. Or I can make a commit in the morning.

**Comment by karlcow** [comment]
@miketaylr Done.
